development:
  adapter: mysql2
  encoding: utf8
  database: historyse_development
  pool: 5
  timeout: 5000
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: historyse_test
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: historyse
  pool: 5
  timeout: 5000
  username: root
  password:
